/* MediLuna — içerik kütüphanesi (tamamı özgün, kendi yazdığımız metinler) */
"use strict";

/* v1 LANSMAN: tüm içerik ücretsiz — v1.1'de RevenueCat ile gerçek abonelik
   gelince false yapılacak (kilitler ve paywall geri döner) */
const LANSMAN_MODU = true;

const CATS = [
  { id: "hepsi",     name: "Hepsi" },
  { id: "stres",     name: "Stres" },
  { id: "kaygi",     name: "Kaygı" },
  { id: "uyku",      name: "Uyku" },
  { id: "odak",      name: "Odak" },
  { id: "ozguven",   name: "Özgüven" },
  { id: "iliskiler", name: "İlişkiler" },
  { id: "ofke",      name: "Öfke" },
  { id: "sukran",    name: "Şükran" },
  { id: "sefkat",    name: "Öz-Şefkat" },
];

const CAT_ART = {
  stres: ["😮‍💨", "linear-gradient(135deg,#2b5876,#4e4376)"],
  kaygi: ["🌊", "linear-gradient(135deg,#134E5E,#2d7d6e)"],
  uyku: ["🌙", "linear-gradient(135deg,#141E30,#3a4d6b)"],
  odak: ["🎯", "linear-gradient(135deg,#1e3c72,#2a5298)"],
  ozguven: ["💪", "linear-gradient(135deg,#4b3869,#7a5a96)"],
  iliskiler: ["💛", "linear-gradient(135deg,#5c4a2e,#8a6d3b)"],
  ofke: ["🌋", "linear-gradient(135deg,#5c2b2b,#8a4b3b)"],
  sukran: ["🌻", "linear-gradient(135deg,#4a4a1e,#7a6d2b)"],
  sefkat: ["🌸", "linear-gradient(135deg,#5a2e4d,#8a5a7a)"],
};

/* Özel çizim ikon seti (stroke tabanlı, currentColor) */
const ICONS = {
  sun: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4.1"/><path d="M12 2.6v2.3M12 19.1v2.3M2.6 12h2.3M19.1 12h2.3M5.2 5.2l1.6 1.6M17.2 17.2l1.6 1.6M18.8 5.2l-1.6 1.6M6.8 17.2l-1.6 1.6"/></svg>',
  compass: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.6"/><path d="M15.4 8.6l-2 4.8-4.8 2 2-4.8z"/></svg>',
  moon: '<svg viewBox="0 0 24 24"><path d="M19.8 14.2A8.2 8.2 0 1 1 9.8 4.2a6.6 6.6 0 0 0 10 10z"/></svg>',
  wind: '<svg viewBox="0 0 24 24"><path d="M3 8.2h8.8a2.3 2.3 0 1 0-2.2-3M3 12.6h12.6a2.4 2.4 0 1 1-2.3 3.1M3 17h6.4a2 2 0 1 1-1.9 2.6"/></svg>',
  user: '<svg viewBox="0 0 24 24"><circle cx="12" cy="8.2" r="3.5"/><path d="M5.2 19.8a6.8 6.8 0 0 1 13.6 0"/></svg>',
  rain: '<svg viewBox="0 0 24 24"><path d="M7.2 14.5a4.6 4.6 0 1 1 .7-9.1A5.5 5.5 0 0 1 18.6 7a3.4 3.4 0 0 1-1.1 6.6H7.2z"/><path d="M8.4 17.2l-1 2.6M12.4 17.2l-1 2.6M16.4 17.2l-1 2.6"/></svg>',
  ocean: '<svg viewBox="0 0 24 24"><path d="M2.5 9.2c2.4 0 2.4 1.9 4.8 1.9s2.4-1.9 4.7-1.9 2.4 1.9 4.8 1.9 2.4-1.9 4.7-1.9M2.5 15c2.4 0 2.4 1.9 4.8 1.9s2.4-1.9 4.7-1.9 2.4 1.9 4.8 1.9 2.4-1.9 4.7-1.9"/></svg>',
  waterfall: '<svg viewBox="0 0 24 24"><path d="M4.5 4.5h9M8 4.5c.2 4.6-.8 8.3-3.4 11.6M12.5 4.5c-.1 5.2 1 8.7 5.4 11.4"/><path d="M3.5 19c2.2 1.4 4.6 1.4 6.8 0M13.5 19.4c2 1.2 4.2 1.2 6.2 0"/></svg>',
  farm: '<svg viewBox="0 0 24 24"><path d="M4.5 19.5V10L12 4.8 19.5 10v9.5z"/><path d="M9.8 19.5v-5.4h4.4v5.4M4.5 12.6L12 7.6l7.5 5"/></svg>',
  fire: '<svg viewBox="0 0 24 24"><path d="M12 3.6c.7 3-3.6 4.9-3.6 8.6a4.9 4.9 0 0 0 9.8.2c0-3.8-2.8-5-3.2-8.8-.9.9-1.8 2.1-1.5 3.6-.9-.9-1.5-2.1-1.5-3.6z"/></svg>',
  forest: '<svg viewBox="0 0 24 24"><path d="M12 3.2l4.6 6.4h-2.7l3.7 5.6H6.4l3.7-5.6H7.4z"/><path d="M12 15.2v5"/><circle cx="19.4" cy="4.6" r="1.1"/></svg>',
  radio: '<svg viewBox="0 0 24 24"><rect x="4" y="9.2" width="16" height="9.8" rx="2"/><path d="M7.5 9.2l8.5-4.7"/><circle cx="9.2" cy="14.1" r="2.1"/><path d="M14.2 12.6h3.6M14.2 15.6h3.6"/></svg>',
  tone: '<svg viewBox="0 0 24 24"><path d="M2.5 12c1.6-5.8 3.2-5.8 4.8 0s3.2 5.8 4.7 0 3.2-5.8 4.8 0 3.2 5.8 4.7 0"/></svg>',
  noise: '<svg viewBox="0 0 24 24"><path d="M4 14.5v-5M8 17.5V6.5M12 19.5V4.5M16 16.5V7.5M20 13.5v-3"/></svg>',
};

/* Duygu ölçeği (duygu günlüğü) */
const MOODS = [
  [1, "😖", "Gergin"],
  [2, "😕", "Yorgun"],
  [3, "😐", "İdare eder"],
  [4, "😌", "Sakin"],
  [5, "🤩", "Harika"],
];

/* Rehberli meditasyonlar — lines: [saniye, metin] */
const MEDITATIONS = [
  {
    id: "m1", cat: "stres", title: "Omuzlardaki Yük", dur: 5, sound: "rain", premium: false,
    lines: [
      [0,   "Rahat bir pozisyon al. Gözlerini yavaşça kapat."],
      [20,  "Derin bir nefes al… ve bırak. Omuzlarının düştüğünü hisset."],
      [50,  "Bugün taşıdığın her şeyi bir an için yere bırakıyorsun."],
      [90,  "Nefes aldıkça göğsünün genişlediğini fark et."],
      [130, "Verdiğin her nefesle gerginlik biraz daha eriyor."],
      [180, "Omuzların, çenen, alnın… hepsi yumuşuyor."],
      [230, "Sadece bu an var. Yağmurun sesi ve senin nefesin."],
      [270, "Yavaşça parmaklarını oynat. Hazır olduğunda gözlerini aç."],
    ],
  },
  {
    id: "m2", cat: "stres", title: "5 Dakikada Sıfırla", dur: 5, sound: "ocean", premium: false,
    lines: [
      [0,   "Bu beş dakika sadece senin. Telefonu çevir, dünyayı beklet."],
      [25,  "Burnundan dört sayarak nefes al… bir, iki, üç, dört."],
      [55,  "Ağzından altı sayarak ver. Dalga geri çekilir gibi."],
      [95,  "Zihninde düşünceler belirebilir. Sorun değil; bulut gibi geçmelerine izin ver."],
      [140, "Her nefes bir dalga. Geliyor… ve gidiyor."],
      [190, "Vücudunda gevşeyen yerleri tek tek fark et."],
      [240, "Kendine teşekkür et. Durmayı seçtin, bu bir güç."],
      [280, "Gözlerini açtığında daha hafif olacaksın."],
    ],
  },
  {
    id: "m3", cat: "kaygi", title: "Fırtınada Liman", dur: 7, sound: "wind", premium: false,
    lines: [
      [0,   "Kaygı bir fırtınaysa, nefesin senin limanın. Gözlerini kapat."],
      [30,  "Ayaklarının yere değdiğini hisset. Yer seni taşıyor."],
      [70,  "Şu an güvendesin. Bu cümleyi içinden tekrar et: Şu an güvendeyim."],
      [120, "Kaygı geleceğe dair bir hikâye anlatır. Sen şimdiye dön."],
      [180, "Beş şey say: duyduğun sesler… nefesin… kalbin…"],
      [240, "Rüzgâr dışarıda essin. Senin içinde sessiz bir oda var."],
      [310, "O odada otur. Acele etme."],
      [380, "Hazır olduğunda derin bir nefesle geri dön."],
    ],
  },
  {
    id: "m4", cat: "kaygi", title: "Düşünce Bulutları", dur: 6, sound: "ciftlik", premium: true,
    lines: [
      [0,   "Sırt üstü bir çayırda uzandığını hayal et. Uzakta bir çiftlik var."],
      [30,  "Gökyüzünde bulutlar var. Her bulut bir düşüncen."],
      [75,  "Bir düşünce geldiğinde onu bulutun üstüne koy."],
      [130, "Ve izle… bulut ağır ağır süzülüp gidiyor."],
      [190, "Sen gökyüzüsün. Düşünceler sadece geçici bulutlar."],
      [250, "Gökyüzü hiçbir buluta tutunmaz. Sen de tutunma."],
      [310, "Son bir kez: geniş, sonsuz ve sakinsin."],
    ],
  },
  {
    id: "m5", cat: "odak", title: "Tek Nokta", dur: 5, sound: "white", premium: false,
    lines: [
      [0,   "Dik otur. Zihnini tek bir noktaya davet ediyoruz: nefesine."],
      [25,  "Burnundan giren havanın serinliğini fark et."],
      [60,  "Zihin kaçtı mı? Normal. Nazikçe geri getir. Bu bir tekrar, ceza değil."],
      [110, "Her geri dönüş, odak kasını güçlendirir."],
      [160, "Nefes… sadece nefes. Başka görev yok."],
      [210, "Şimdi bu berraklığı günün geri kalanına taşı."],
      [270, "Gözlerini aç. Zihnin keskin, için sakin."],
    ],
  },
  {
    id: "m6", cat: "odak", title: "Derin Çalışma Öncesi", dur: 3, sound: "white", premium: true,
    lines: [
      [0,   "Üç dakika sonra işine tam güçle döneceksin."],
      [20,  "Önce zihnindeki sekmeleri tek tek kapat."],
      [50,  "Yapılacaklar listesi şimdilik beklemede. Sadece nefes."],
      [90,  "Yapacağın tek işi zihninde canlandır. Sadece onu."],
      [130, "Nefes al: enerji. Nefes ver: dağınıklık."],
      [160, "Hazırsın. Tek nokta, tam güç."],
    ],
  },
  {
    id: "m7", cat: "ozguven", title: "İç Sesini Yumuşat", dur: 6, sound: "rain", premium: true,
    lines: [
      [0,   "Gözlerini kapat. Bugün kendine nasıl konuştuğunu hatırla."],
      [35,  "O sesi bir arkadaşına kullanır mıydın?"],
      [85,  "Şimdi aynı cümleyi şefkatle yeniden kur."],
      [140, "İçinden söyle: Elimden geleni yapıyorum ve bu değerli."],
      [200, "Hataların seni küçültmez; büyüdüğünün kanıtıdır."],
      [260, "Omuzlarını geri al. Yerin burası, hak ederek buradasın."],
      [320, "Bu sesi yanına al. O artık senin iç sesin."],
    ],
  },
  {
    id: "m8", cat: "iliskiler", title: "Şefkat Nefesi", dur: 6, sound: "forest", premium: true,
    lines: [
      [0,   "Sevdiğin birini zihninde canlandır. Yüzünü, gülüşünü."],
      [40,  "Nefes alırken ona iyi dilekler gönder: Huzurlu ol."],
      [100, "Nefes ver: Sağlıklı ol. Güvende ol."],
      [160, "Şimdi aynı dilekleri kendine gönder. Sen de hak ediyorsun."],
      [230, "Zor bir ilişkin varsa, o kişiye de küçük bir dilek dene."],
      [290, "Şefkat bir kas. Her nefeste güçleniyor."],
    ],
  },
  {
    id: "m9", cat: "uyku", title: "Bedeni Uğurlama", dur: 8, sound: "rain", premium: false,
    lines: [
      [0,   "Yatağına iyice yerleş. Bu meditasyonun sonunda uyuyakalabilirsin; amaç da bu."],
      [40,  "Ayak parmaklarından başla. Onlara 'iyi geceler' de, bırak ağırlaşsınlar."],
      [110, "Bacakların yatağa gömülüyor. Sıcak ve ağır."],
      [190, "Karnın, göğsün… nefesinle birlikte yumuşuyor."],
      [270, "Ellerin, kolların… bugün çok çalıştılar. Artık dinlensinler."],
      [350, "Yüzün… çenen gevşiyor, alnın düzleşiyor."],
      [420, "Yağmur camda, sen güvendesin. Her şey yarına kadar bekleyebilir."],
      [460, "Uykuya teslim ol…"],
    ],
  },
  {
    id: "m10", cat: "uyku", title: "Gece Yarısı Uyanınca", dur: 5, sound: "ocean", premium: true,
    lines: [
      [0,   "Uyandın ve zihin hemen çalışmaya başladı. Sorun değil, buradayız."],
      [30,  "Saate bakma. Gece senin düşmanın değil."],
      [80,  "Nefesini say: dört al… altı ver…"],
      [140, "Dalgalar sahile vuruyor. Her dalga bir düşünceyi alıp götürüyor."],
      [200, "Beden zaten yorgun. Ona sadece izin vermen gerek."],
      [260, "Bırak… okyanus seni sallasın…"],
    ],
  },
  {
    id: "m11", cat: "stres", title: "Sabah Zırhı", dur: 4, sound: "ciftlik", premium: true,
    lines: [
      [0,   "Güne başlamadan önce dört dakikalık zırhını kuşan."],
      [25,  "Bugün seni ne bekliyorsa, onu karşılayacak gücün var."],
      [70,  "Nefes al: sabır. Nefes ver: acele."],
      [120, "Bugün kontrol edemeyeceğin şeyler olacak. Onları şimdiden bırak."],
      [175, "Kontrol edebildiğin tek şey: kendi adımın, kendi nefesin."],
      [220, "Gözlerini aç. Gün seni bekliyor, sen hazırsın."],
    ],
  },
  {
    id: "m12", cat: "ozguven", title: "Aynadaki Dost", dur: 5, sound: "selale", premium: false,
    lines: [
      [0,   "Bir şelalenin yanında, bir ayna karşısında durduğunu hayal et."],
      [30,  "Karşındaki kişiye ilk bakışta ne söylerdin?"],
      [80,  "Şimdi ona bir dostun gözüyle bak. Yorgunluğunu, çabasını gör."],
      [140, "O kişi bugüne kadar her zorluğu atlattı. Kanıt: burada duruyor."],
      [200, "Ona söyle: Seninle gurur duyuyorum."],
      [255, "Aynadaki dost, sensin."],
    ],
  },
  {
    id: "m13", cat: "odak", title: "İlk Nefes", dur: 3, sound: "white", premium: false,
    lines: [
      [0, "Hoş geldin. Bu ilk günün. Kendinden hiçbir şey bekleme; sadece burada ol."],
      [25, "Rahat bir pozisyon al. Gözlerini yavaşça kapat ya da bakışını yere indir."],
      [50, "Şimdi nefesini fark et. Onu değiştirme; zaten kendi kendine akıyor."],
      [78, "Havanın içeri girişini hisset… ve dışarı çıkışını. Şimdilik tek işin bu."],
      [108, "Zihnin dağılırsa üzülme. Fark etmek de çalışmanın parçası. Nazikçe nefese dön."],
      [152, "Gözlerini yavaşça aç. İlk adımı attın. Yarın yeniden buluşuruz."],
    ],
  },
  {
    id: "m14", cat: "stres", title: "Bedeni Dinlemek", dur: 4, sound: "rain", premium: false,
    lines: [
      [0, "Hoş geldin. Dün nefesi fark etmeyi denemiştik. Bugün bedenine kulak vereceğiz."],
      [25, "Rahatça yerleş. Derin bir nefes al… ve bırak. Omuzların kendiliğinden yumuşasın."],
      [52, "Dikkatini alnına getir. Orada bir gerginlik var mı? Sadece fark et."],
      [82, "Yavaşça aşağı in: çene, boyun, omuzlar. Tuttuğun yerlere nefesini gönder."],
      [115, "Şimdi sırtın, karnın, ellerin. Her nefes verişte biraz daha bırak."],
      [155, "Bacaklarına ve ayaklarına in. Bedeninin yere değdiği her noktayı hisset."],
      [205, "Bütün bedenini tek parça olarak duyumsa. Gözlerini aç. Bu dinleme alışkanlığı artık seninle."],
    ],
  },
  {
    id: "m15", cat: "kaygi", title: "Nehirdeki Yapraklar", dur: 4, sound: "wind", premium: false,
    lines: [
      [0, "Hoş geldin. Dün bedenindeki gerginlikleri fark etmiştin. Bugün zihnine bakacağız."],
      [25, "Gözlerini kapat. Birkaç nefesle buraya yerleş. Acele yok."],
      [52, "Bir nehir kenarında oturduğunu hayal et. Su sakin sakin akıyor."],
      [82, "Aklına gelen her düşünceyi, suyun üstünde süzülen bir yaprağa koy."],
      [115, "Yaprak akıntıyla uzaklaşsın. Tutmana gerek yok, itmene de. Sadece izle."],
      [158, "Bir düşünceye kapıldığını fark edersen, kıyıya geri otur. Yeni bir yaprak her zaman var."],
      [205, "Nehri orada bırak. Nefesine dön ve gözlerini aç. Düşünceler gelir, geçer; sen kalırsın."],
    ],
  },
  {
    id: "m16", cat: "odak", title: "Seslerin Çapası", dur: 4, sound: "forest", premium: false,
    lines: [
      [0, "Hoş geldin. Dün düşünceleri nehirde uğurlamıştık. Bugün çapamız sesler olacak."],
      [25, "Rahatça otur. Gözlerini kapat. Bir iki derin nefesle yerleş."],
      [52, "Şimdi kulaklarını aç. Çevrendeki en uzak sesi bul."],
      [82, "Sesleri adlandırmana gerek yok. İyi ya da kötü deme; sadece duy."],
      [115, "Yakındaki seslere gel. Belki kendi nefesinin sesi, belki odanın uğultusu."],
      [158, "Zihnin dalarsa herhangi bir ses seni geri çağırsın. Ses, şimdiye açılan bir kapı."],
      [205, "Son bir kez dinle… Gözlerini aç. Sesler hep buradaydı; sen de artık buradasın."],
    ],
  },
  {
    id: "m17", cat: "kaygi", title: "Dalgalara İzin", dur: 5, sound: "ocean", premium: false,
    lines: [
      [0, "Hoş geldin. Dün sesleri çapa yapmıştık. Bugün içeride olup bitene yer açacağız."],
      [24, "Gözlerini kapat. Nefesin doğal ritmine bırak kendini."],
      [50, "Bir kıyıda durduğunu düşün. Önünde uçsuz bucaksız bir deniz. Dalgalar geliyor ve çekiliyor."],
      [78, "Şu an içinde bir duygu var mı? Kaygı, sıkıntı, belki sadece yorgunluk. Ne varsa, olsun."],
      [108, "O duyguyu bir dalga gibi düşün. Yükseliyor… tepe yapıyor… ve iniyor."],
      [140, "Dalgayla savaşma. Kum gibi ol; bırak üzerinden geçsin, sonra çekilsin."],
      [175, "Duygu bedeninde bir yerde duruyorsa, oraya nefes gönder. Yer aç, genişle."],
      [220, "Her dalga gider. Hiçbiri kalıcı değil. Sen kıyısın; dalga değilsin."],
      [268, "Nefesinle geri dön. Gözlerini aç. Duygularına yer açmak, sessiz bir beceri; bugün onu çalıştın."],
    ],
  },
  {
    id: "m18", cat: "sefkat", title: "İçindeki Nazik Ses", dur: 5, sound: "selale", premium: false,
    lines: [
      [0, "Hoş geldin. Dün duygulara yer açmıştık. Bugün kendinle konuşma biçimine bakacağız."],
      [24, "Rahatça otur. İstersen bir elini kalbinin üstüne koy. Gözlerini kapat."],
      [50, "Avucunun sıcaklığını hisset. Bu sıcaklık, kendine getirdiğin küçük bir armağan."],
      [78, "İçindeki sesi bir dinle. Gün boyunca sana nasıl sesleniyor? Sert mi, aceleci mi?"],
      [108, "Şimdi o tonu yumuşat. Sevdiğin bir dosta nasıl konuşuyorsan, kendine de öyle seslen."],
      [140, "İçinden şu cümleyi geçir: Bugün elimden geleni yaptım. Bu bana yeter."],
      [178, "Zorlandığın bir anını hatırla. O anki haline şimdi nazikçe bak. Suçlamadan, sadece anlayışla."],
      [222, "Nefes alırken bu yumuşaklığı içine çek. Nefes verirken sertliği bırak."],
      [268, "Elini indir, gözlerini aç. O nazik ses artık senin; gün içinde onu istediğinde çağırabilirsin."],
    ],
  },
  {
    id: "m19", cat: "odak", title: "Yanındaki Sessizlik", dur: 6, sound: "ciftlik", premium: false,
    lines: [
      [0, "Hoş geldin. Bugün yedinci gün. Altı gündür adım adım geldin; bugün hepsini birleştiriyoruz."],
      [24, "Gözlerini kapat. Burası artık tanıdık bir yer. Nefesin seni karşılasın."],
      [50, "Kısaca hatırla: nefesi izledin, bedeni dinledin, düşünceleri suya bıraktın."],
      [78, "Sesleri duydun, dalgalara yer açtın, iç sesini yumuşattın. Hepsi hâlâ seninle."],
      [108, "Şimdi bir sabah düşün. Çayını ya da kahveni alıyorsun. Fincanın sıcaklığı avucunda."],
      [140, "İlk yudumu tam dikkatle iç. Kokusu, buharı, tadı. İşte bu da bir meditasyon."],
      [175, "Bir de yürüdüğünü düşün. Adımlarının yere değişini hisset. Telefon cebinde kalsın; sokak sana yeter."],
      [215, "Gün içinde tek bir derin nefes bile bir dönüş kapısı. Uzun olması gerekmez; hatırlaman yeter."],
      [270, "Yedi gün bitti ama bir şey başladı. Bu sessizliği artık yanında taşıyorsun."],
      [330, "Gözlerini aç. Kendi hızında devam et. Yolun açık olsun."],
    ],
  },
  {
    id: "m20", cat: "stres", title: "Bir Nefeslik Mola", dur: 4, sound: "rain", premium: false,
    lines: [
      [0, "Olduğun yerde kal. Gözlerini kapatman gerekmiyor; bakışını yumuşat, tek bir noktaya sabitleme."],
      [25, "Ayak tabanlarını fark et. Zemin seni taşıyor; ağırlığını iki ayağına eşit dağıt."],
      [50, "Derin bir nefes al… burnundan. Ve yavaşça ver. Çenendeki gerginliği bırak."],
      [80, "Omuzlarını kulaklarına doğru hafifçe kaldır… ve bırak düşsünler. Bir kez daha."],
      [115, "Etraftaki sesler gelip geçsin. Sen sadece nefesinin girip çıkışını izle. Hepsi bu."],
      [155, "Bu bekleyiş bir kayıp değil; sana kalan küçük bir boşluk. O boşluğun içinde dur."],
      [205, "Bir nefes daha al. Hazır olduğunda günün akışına, biraz daha hafif, geri dön."],
    ],
  },
  {
    id: "m21", cat: "kaygi", title: "Sahne Öncesi Nefes", dur: 5, sound: "ocean", premium: true,
    lines: [
      [0, "Bir yer bul; dik ama rahat otur ya da ayakta dur. Gözlerini kapatabilirsin."],
      [25, "Kalbin hızlı atıyorsa sorun yok. Bedenin önemli bir an için hazırlanıyor; bu bir alarm değil, bir hazırlık."],
      [50, "Burnundan dört sayarak nefes al… bir, iki, üç, dört. Altı sayarak ver. Veriş, alıştan uzun olsun."],
      [78, "Bir kez daha. Alırken göğsün genişlesin… verirken omuzların yumuşasın."],
      [108, "Avuçlarını fark et. Belki hafif terli, belki serin. Onları bir kez sık… ve aç. Enerji orada, senin emrinde."],
      [140, "Şimdi o anı gözünün önüne getir. İçeri giriyorsun; adımların yavaş, nefesin seninle."],
      [175, "İlk cümleni söylediğini hayal et. Sesin titrese bile devam ediyorsun. Devam etmek yeterli."],
      [215, "İçindeki bu kıpırtıya yeni bir ad ver: heyecan. Aynı enerji; sadece yönü artık sana ait."],
      [260, "Son bir derin nefes. Hazırsın. Gözlerini aç ve o ana kendi temponla yürü."],
    ],
  },
  {
    id: "m22", cat: "uyku", title: "Ondan Geriye", dur: 7, sound: "rain", premium: true,
    lines: [
      [0, "Yatağına yerleş. Yorganın ağırlığını, başının yastıkta bıraktığı izi hisset."],
      [30, "Birazdan ondan geriye sayacağız. Her sayıda bedenin biraz daha ağırlaşacak, zihnin biraz daha yavaşlayacak."],
      [60, "On… Nefesin kendi ritmini bulsun. Dokuz… Alnındaki çizgiler yumuşasın."],
      [95, "Sekiz… Göz kapakların ağırlaşıyor. Yedi… Çenen gevşiyor, dişlerin birbirine değmiyor."],
      [130, "Altı… Omuzların yatağa gömülüyor. Beş… Kolların ağır, sıcak, sakin."],
      [170, "Dört… Yağmurun sesi düşüncelerinin arasını dolduruyor. Boşluklar büyüyor."],
      [215, "Üç… Bacakların, gün boyu taşıdıkları her şeyi bırakıyor."],
      [260, "İki… Düşünceler uzaktan geçen ışıklar gibi; bakmana gerek yok."],
      [310, "Bir… Artık hiçbir yere gitmen gerekmiyor. Tam olman gereken yerdesin."],
      [365, "Sayılar bitti. Sadece nefes, yağmur ve ağırlık kaldı. Kendini gecenin akışına bırakabilirsin."],
    ],
  },
  {
    id: "m23", cat: "uyku", title: "Günü Rafa Kaldır", dur: 6, sound: "wind", premium: false,
    lines: [
      [0, "Uzan ve gözlerini kapat. Bugün her neyse, olduğu gibi kalsın; şimdi sadece kapanış vakti."],
      [28, "Rüzgârın sesini duy. Gün boyu biriken ne varsa, o ses gibi gelip geçmesine izin ver."],
      [56, "Zihninde sessiz bir oda hayal et. Duvarlarında boş, geniş raflar var."],
      [88, "Bugünden bir an seç. İyi ya da kötü demeden, onu elinde bir nesne gibi tut… ve rafa koy."],
      [120, "Bir an daha. Yarım kalan bir iş belki. Yargılamadan, olduğu gibi… rafa."],
      [158, "Söylenmemiş bir söz, küçük bir sevinç, bir yorgunluk… Hepsine rafta yer var."],
      [200, "Raflar sabaha kadar bekleyebilir. Hiçbiri kaybolmayacak; sadece bu gece taşınmayacaklar."],
      [245, "Odanın ışığını yavaşça kıs. Kapıyı usulca örtüyorsun; gün tamamlandı."],
      [295, "Şimdi sadece nefesin ve rüzgâr var. Bırak, gece seni taşısın."],
    ],
  },
  {
    id: "m24", cat: "odak", title: "Işığı Topla", dur: 4, sound: "white", premium: true,
    lines: [
      [0, "Otur ve omurganı nazikçe dikleştir. Bir derin nefes al… ve ver."],
      [25, "Dikkatin şu an dağınık olabilir. Sorun değil; dağılan şey toplanabilir."],
      [50, "Güneş ışığının bir mercekle tek noktada toplandığını düşün. Işık aynı ışık; sadece bir araya geliyor."],
      [80, "Şimdi merceğin nefesin. Her nefes alışta, dağılan dikkatinin bir parçası geri geliyor."],
      [115, "Zihnin başka yere kayarsa fark et, kızma. Merceği hafifçe çevir; ışık yeniden toplansın."],
      [160, "O tek parlak nokta, birazdan döneceğin iş. Şu an sadece o var; gerisi kenarda bekleyebilir."],
      [205, "Bir nefes daha. Gözlerini aç ve o tek noktaya, toplanmış ışığınla dön."],
    ],
  },
  {
    id: "m25", cat: "ozguven", title: "İç Sesin Adı", dur: 5, sound: "selale", premium: true,
    lines: [
      [0, "Rahatça otur. Şelalenin sesi aksın; sen sadece nefesinle burada ol."],
      [25, "Az önce bir şey ters gitti. Bunu değiştirmeye çalışmadan, sadece 'oldu' de. Olan, oldu."],
      [52, "İçinde konuşan sert bir ses olabilir. 'Nasıl yaparsın' diyen ses. Onu şimdi dinleme; sadece fark et."],
      [80, "O sese bir ad ver. Herhangi bir ad. Ad koyduğun şey, sen olmaktan çıkar; misafire dönüşür."],
      [110, "Misafirin söyledikleri birer duygu, kanıt değil. Kanıtlara birlikte bakalım."],
      [145, "Daha önce zor bir durumu toparladığın bir anı hatırla. Bir tane yeter. Onu gözünün önünde tut."],
      [182, "O gün de hata olmuştu belki. Ama devam ettin. Hata bir olaydı; sen olayların toplamısın."],
      [222, "Misafire içinden şunu söyle: 'Seni duydum. Ama bugün kararları ben veriyorum.'"],
      [262, "Derin bir nefes al. Omuzlarını geri aç, başını kaldır. Kaldığın yerden, bir adım."],
    ],
  },
  {
    id: "m26", cat: "iliskiler", title: "Sadece Duymak", dur: 5, sound: "forest", premium: true,
    lines: [
      [0, "Rahat bir pozisyon al. Sırtın dik ama yumuşak olsun. Gözlerini kapatabilirsin."],
      [25, "Bir nefes al… ve yavaşça bırak. Şu an sadece buradasın."],
      [50, "Çevrendeki sesleri fark et. Onları adlandırmadan, sadece duy."],
      [80, "Şimdi birini düşün. Onu dinlerken aklın çoğu zaman cevabını hazırlıyor. Bunu fark etmen yeterli."],
      [110, "Cevabı bırak. İçinden şunu de: Şu an sadece duyuyorum."],
      [145, "O kişinin sesini hayal et. Kelimelerin altındaki tonu dinle. Acele etmeden."],
      [185, "Dinlemek bir hediye. Karşındakine yer açtığında, kendine de yer açıyorsun."],
      [230, "Bir nefes daha al. Bu sessiz dinleme alanı hep seninle."],
      [275, "Hazır olduğunda gözlerini yavaşça aç. Bugün birini sadece duymak için dinle."],
    ],
  },
  {
    id: "m27", cat: "iliskiler", title: "Dalganın Götürdüğü", dur: 6, sound: "ocean", premium: false,
    lines: [
      [0, "Otur ya da uzan. Bedeninin desteklendiği yerleri hisset."],
      [25, "Derin bir nefes al… ve bırak. Omuzların yumuşasın."],
      [50, "Dalgaların sesi gibi, nefesin de gelip gidiyor. Onu izle."],
      [80, "Şimdi nazikçe bir kırgınlığı hatırla. Küçük bir tanesini seç. Zorlamadan."],
      [110, "Bu kırgınlık bedeninde nerede? Göğsünde bir baskı, boğazında bir düğüm olabilir. Sadece fark et."],
      [145, "Bu ağırlığı uzun süredir taşıyorsun. Taşımak bir seçimdi; bırakmak da olabilir."],
      [185, "Bırakmak, olanı onaylamak değil. Sadece elini açmak. Kendi omzunu hafifletmek."],
      [230, "Nefes verirken ağırlığın bir kısmının aktığını hayal et. Dalga geri çekilirken kumdaki izleri alıp götürür gibi."],
      [280, "Tamamı gitmese de olur. Bugün bir avuç bıraktın; bu yeterli."],
      [330, "Yavaşça parmaklarını kıpırdat. Gözlerini aç. Biraz daha hafifsin."],
    ],
  },
  {
    id: "m28", cat: "ofke", title: "İzleyen Kıyı", dur: 4, sound: "fire", premium: true,
    lines: [
      [0, "Dur. Ayaklarını yere bas. Bir nefes al."],
      [25, "Öfke bir dalga gibi yükseliyor olabilir. Onunla savaşma; sadece izle."],
      [50, "Bedeninde sıcaklığı ara. Göğsünde mi, ellerinde mi, yüzünde mi? Bulduğun yere nefes gönder."],
      [80, "Bu sıcaklık bir bilgi. Sana önemli bir şeye dokunulduğunu söylüyor. Onu duydun."],
      [115, "Nefes verişini uzat. İçeri dört say… dışarı altı say. Alevin köze dönmesini izle."],
      [160, "Dalga yükseldi ve şimdi iniyor. Sen dalga değilsin; onu izleyen kıyısın."],
      [210, "Bir nefes daha. Hazır olduğunda gözlerini aç. Ne yapacağını artık sen seçiyorsun."],
    ],
  },
  {
    id: "m29", cat: "sukran", title: "Üç Küçük An", dur: 4, sound: "forest", premium: true,
    lines: [
      [0, "Rahatça otur. Gözlerini kapat. Bir nefes al ve bırak."],
      [20, "Bugünün içinde küçük iyilikler saklı. Şimdi onları toplamaya çıkıyorsun."],
      [45, "İlk anı bul. Belki sıcak bir bardak, bir gülümseme, pencereden düşen ışık. Onu yeniden gör."],
      [75, "O anda bedenin nasıldı? O küçük rahatlığı şimdi tekrar hisset."],
      [110, "İkinci anı çağır. Sıradan görünen ama iyi gelen bir şey. Yanında biraz kal."],
      [155, "Ve üçüncüsü. Küçücük olabilir. Onu avucuna al, ağırlığını hisset. Üç an; bugünün sessiz hazinesi."],
      [205, "Bu anlar hep oradaydı; sen fark ettin. Gözlerini açtığında bir tane daha bulabilirsin."],
    ],
  },
  {
    id: "m30", cat: "sefkat", title: "İçindeki Dost", dur: 5, sound: "rain", premium: true,
    lines: [
      [0, "Otur ve bedeninin yerleştiğini hisset. Yağmurun sesi arka planda kalsın."],
      [25, "Bir elini göğsüne koyabilirsin. Avucunun sıcaklığını fark et."],
      [50, "Bugün zordu. Bunu kabul etmek için büyük bir sebep gerekmiyor. Zordu, o kadar."],
      [80, "Şimdi en yakın dostunu düşün. Aynı günü o yaşasaydı, ona ne derdin?"],
      [110, "Muhtemelen yumuşak bir şey derdin. Suçlamazdın. Acele ettirmezdin."],
      [145, "O cümleyi şimdi kendine söyle. İçinden, kendi adınla: Bugün elinden geleni yaptın."],
      [185, "Kendine dostluk göstermek bencillik değil. Aynı anlayışı içeri döndürmek."],
      [230, "Avucunun altındaki sıcaklık… O dost sensin. Hep yanındaydın."],
      [275, "Yavaşça derin bir nefes al. Gözlerini aç. Kendine biraz daha yumuşak davranarak devam et."],
    ],
  },
];

/* Uyku hikayeleri — özgün kısa hikayeler
   Kural: her gün 1 hikaye ücretsizdir (rotasyon), diğerleri Premium ister. */
const STORIES = [
  {
    id: "s1", title: "Fener Bekçisinin Gecesi", dur: 11, sound: "ocean", emoji: "🗼",
    lines: [
      [0, "Yatağına iyice yerleş, sırtın yumuşasın. Omuzların usulca aşağı insin, nefesin denizin kıyısına kadar uzansın."],
      [54, "Küçük bir adanın ucunda, yosun ve tuz kokan bir taş fener duruyor. İçeride Kemal, yılların yorgunluğunu tatlı tatlı taşıyor."],
      [108, "Fenerin kalın duvarları serin ve pürüzlü. Kemal avucunu taşa değdiriyor, gündüzden kalan hafif sıcaklığı parmak uçlarında hissediyor."],
      [162, "Yukarıda büyük lamba, sabırla dönüyor. Işığı geniş bir yay çiziyor, karanlık suyu okşayıp usulca geri dönüyor."],
      [216, "Pencerenin ötesinde deniz, koyu ve dingin. Dalgalar acele etmeden geliyor, kayalara değip iç geçirir gibi çekiliyor."],
      [272, "Uzakta, ufkun kıyısında, birkaç teknenin soluk feneri titriyor. Sanki gökyüzünden düşmüş, suya yerleşmiş küçük yıldızlar."],
      [328, "Kemal camdan uzaklaşıp eski ahşap sandalyesine oturuyor. Tahtalar tanıdık bir sesle hafifçe gıcırdıyor, sonra susuyor."],
      [384, "Sobanın üstündeki demlikten ince bir buhar yükseliyor. Odaya kekik ve ıhlamurun sıcak, yumuşak kokusu yayılıyor."],
      [440, "Işık yeniden dönüyor, duvarda solgun bir hâle geziniyor. Kemal gözleriyle onu izliyor, aydınlık geldikçe içi ısınıyor."],
      [496, "Dışarıda rüzgâr çok hafif. Fenerin tepesindeki eski çıngırağı ancak duyulur bir tınıyla, uykulu uykulu sallıyor."],
      [552, "Kemal battaniyesini dizlerine çekiyor. Yünün yumuşaklığı bacaklarını sarıyor, sıcaklık yavaşça göğsüne doğru tırmanıyor."],
      [608, "Denizin sesi bir ninniye dönüşüyor artık. Gel, git, gel, git; nefesiyle aynı sakin ölçüde salınıyor."],
      [664, "Göz kapakları ağırlaşıyor, lambanın dönüşü uzaklarda bir parıltıya karışıyor. Fener onun yerine bekliyor bu gece."],
      [720, "Kemal başını arkaya bırakıyor, kayalar, tekneler, ışık, hepsi yumuşacık bir sise gömülüyor."],
      [776, "Nefesi denizle birlikte iniyor, çıkıyor; usulca, daha da usulca, karanlık kadifeye teslim oluyor…"],
    ],
  },
  {
    id: "s2", title: "Kar Altındaki Köy", dur: 10, sound: "wind", emoji: "🏔️",
    lines: [
      [0, "Gözlerini yum, çeneni gevşet, avuçların açılsın. Bırak vücudun yatağa iyice gömülsün, ağırlığını yorgana bıraksın."],
      [52, "Dağların arasına saklanmış küçük bir köy var. Akşam iniyor, gökyüzü yumuşak, kurşun rengi bir sessizliğe bürünüyor."],
      [104, "İlk kar taneleri usulca süzülüyor. Aceleleri yok; havada dönerek, salınarak, bir tüy hafifliğiyle yere iniyorlar."],
      [158, "Elif penceresinin önünde duruyor. Camdaki buğuya parmağını değdiriyor, dışarıdaki beyaz sessizliği seyre dalıyor."],
      [212, "Sokak lambası sarı, sıcak bir ışık saçıyor. Kar taneleri o aydınlıkta bir an parlıyor, sonra usulca gölgeye karışıyor."],
      [268, "Evlerin bacalarından ince duman şeritleri yükseliyor. Yanan odunun tatlı, is kokusu soğuk havaya karışıyor."],
      [324, "Elif ocağın başına dönüyor. Alevler çıtırdıyor, yüzüne turuncu bir sıcaklık vuruyor, yanakları hafifçe ısınıyor."],
      [380, "Elinde buğulanan bir bardak var. İçindeki sıcak, baldan ve tarçından bir tatlılıkla avuçlarını ısıtıyor."],
      [436, "Dışarıda kar kalınlaşıyor, çatıları, çitleri, patikaları yumuşak bir örtüyle sarıyor. Köy bembeyaz bir yastığa yaslanıyor."],
      [492, "Ses diye bir şey kalmıyor neredeyse. Yalnızca karın üstüne düşen karın, o incecik, mırıltılı fısıltısı."],
      [548, "Elif battaniyesine sarılıp pencerenin yanındaki koltuğa büzülüyor. Yünün sıcaklığı omuzlarından aşağı yayılıyor."],
      [604, "Lambanın ışığı hâlâ orada, sabırlı ve sıcak. Kar taneleri o hâlenin içinde uykulu uykulu dans ediyor."],
      [660, "Göz kapakları ağırlaşıyor. Beyaz köy, sarı ışık, hepsi giderek yumuşayan bir düşe dönüşüyor."],
      [716, "Elif başını yastığa bırakıyor. Kar sessizce yağmayı sürdürüyor, dışarısı ve içerisi aynı huzura gömülüyor…"],
    ],
  },
  {
    id: "s3", title: "Gece Treni", dur: 12, sound: "rain", emoji: "🚂",
    lines: [
      [0, "Sırtını yasla, bacaklarını uzat, ellerini karnının üzerinde kavuştur. Nefesin yavaşlasın, tenin ağırlaşsın, gevşesin."],
      [56, "Yağmurlu bir ovada, gece treni usulca ilerliyor. Vagonun içi loş, sıcak, ipeksi bir sarılıkla aydınlanıyor."],
      [112, "Deniz penceresinin yanında oturuyor. Alnını serin cama yaslıyor, dışarıda karanlık ova sessizce akıp gidiyor."],
      [168, "Yağmur damlaları cama vuruyor, incecik izler bırakarak aşağı kayıyor. Her damla küçük, parlak bir yol çiziyor."],
      [226, "Tekerlekler raylarda sabit bir ritim tutturuyor. Tık-tık, tık-tık; uykulu bir kalp atışı gibi düzenli, gibi yumuşak."],
      [282, "Deniz dizlerine yumuşak bir battaniye çekiyor. Yünün ağırlığı bacaklarını sarıyor, sıcaklık usulca yukarı süzülüyor."],
      [338, "Dışarıda uzaktaki bir çiftlik evinin ışığı görünüp kayboluyor. Karanlıkta titreyen, sıcak, minik bir nokta."],
      [394, "Vagon hafifçe sağa sola sallanıyor. Deniz bu tatlı beşik sallantısına bırakıyor kendini, omuzları iyice gevşiyor."],
      [450, "Camdaki damlalar çoğalıyor, birleşiyor, incecik nehirlere dönüşüyor. Deniz onların yavaş yolculuğunu izliyor."],
      [506, "Yağmurun sesi, tekerleğin ritmiyle kaynaşıyor. İkisi birlikte usul bir ninni söylüyor kulağına."],
      [562, "Tavandaki soluk ışık dizlerine, ellerine yumuşacık düşüyor. Deniz avuçlarındaki sıcaklığı hissediyor, içi rahatlıyor."],
      [618, "Ova sonsuzmuş gibi uzanıyor karanlıkta. Tren acele etmiyor, hiçbir yere yetişme telaşı taşımıyor bu gece."],
      [674, "Göz kapakları ağırlaşıyor. Damlalar, ışıklar, ritim, hepsi yumuşak bir puslu düşe karışıyor."],
      [730, "Deniz başını cama yaslıyor. Tren onu usulca taşıyor, ova, yağmur, gece hep birlikte sürükleniyor."],
      [786, "Tekerlekler yavaşlıyor gibi, nefesi de yavaşlıyor onunla. Tık-tık, tık-tık, gitgide uzaklaşıyor, uykuya karışıyor…"],
    ],
  },
  {
    id: "s4", title: "Zeytin Ağacının Rüyası", dur: 9, sound: "forest", emoji: "🫒",
    lines: [
      [0, "Rahatça uzan, kollarını iki yanına bırak, çeneni gevşet. Nefesin toprağa iner gibi derinleşsin, yavaşlasın."],
      [54, "Ege'de bir tepenin üstünde, sekiz yüz yaşında bir zeytin ağacı duruyor. Gövdesi kalın, kıvrımlı, sabırla bükülmüş."],
      [108, "Akşam güneşi alçalıyor. Yaprakların arasından süzülen ışık, gümüşî bir parıltıyla dallarda salınıyor."],
      [162, "Kabuğu ılık ve pürüzlü, gün boyu emdiği sıcaklığı yavaşça geri veriyor. Bir kertenkele gövdesinde durup ısınıyor."],
      [218, "Aşağıda, kuru otların ve yabani kekiğin kokusu havaya karışıyor. Sıcak, tozlu, tatlı bir yaz kokusu."],
      [274, "Cırcır böcekleri usul usul ötmeye başlıyor. Tek tük başlayan sesler, giderek yumuşak bir uğultuya dönüşüyor."],
      [330, "Ağacın kökleri toprağın derinine uzanıyor. Aşağıda hava serin ve nemli, taşların arasından sessizce dolanıyor."],
      [386, "Hafif bir meltem geliyor denizden. Gümüş yapraklar hışırdıyor, binlerce küçük el gibi usulca çırpınıyor."],
      [442, "Güneş ufka değiyor, gökyüzü şeftali ve gül rengine boyanıyor. Işık iyice yumuşuyor, gölgeler uzuyor."],
      [498, "Ağaç yüzlerce yazın anısını taşıyor gövdesinde. Hepsi sakin, hepsi sessiz, hiçbiri acele etmiyor."],
      [554, "Kekik kokusu koyulaşıyor akşam serinliğiyle. Toprak günün sıcağını bırakıp yavaşça soluk alıyor."],
      [610, "Cırcır böceklerinin uğultusu bir ninniye dönüşüyor. Sürekli, yumuşak, nefes alıp verir gibi salınan bir ses."],
      [666, "Yapraklar son ışıkta bir kez daha parlıyor, sonra gölgeye teslim oluyor. Ağaç dinginliğe iyice gömülüyor."],
      [722, "Kökler serin toprağı sarıyor, gövde gecenin kadifesine yaslanıyor. Tepe usulca kararıyor, sessizliğe bırakıyor kendini…"],
    ],
  },
  {
    id: "s5", title: "Çiftlikte Akşam", dur: 9, sound: "ciftlik", emoji: "🐄",
    lines: [
      [0, "Yatağına iyice yerleş; sırtın yumuşak yastığa gömülsün, omuzların usulca aşağı kaysın."],
      [54, "Bir nefes al, ağır ağır bırak. Şimdi seni akşam serinliğinin çöktüğü küçük bir çiftliğe götürüyorum."],
      [108, "Güneş tepelerin ardına inmiş, gökyüzü bal rengiyle mora dönüyor; hava ılık, tozlu ve tatlı."],
      [162, "Çiftçi Osman ahırın önünde duruyor, avucunda günün son ışığının ılıklığı kalmış gibi."],
      [216, "İnekler otlaktan usul usul dönüyor; her adımda ayaklarının altında kuru saman hışırdıyor."],
      [270, "Boyunlarındaki çanlar yumuşacık çınlıyor; ne acele var ne telaş, yalnızca tembel bir tıngırtı."],
      [324, "Osman kapıyı ardına kadar açıyor; içeriden sıcak saman ve süt kokusu dalga dalga yayılıyor."],
      [378, "İnekler birer birer içeri süzülüyor, her biri kendi köşesine çöküyor, derin bir soluk veriyor."],
      [432, "Uzaktan derenin sesi geliyor; taşların üstünden akıp giden, hiç durmayan yumuşak bir mırıltı."],
      [486, "Osman kucak dolusu taze samanı yayıyor; altın rengi saplar havada döne döne yere iniyor."],
      [540, "Bir fener yakıyor; turuncu ışık ahırın tahta duvarlarında sıcak, titrek gölgeler oynatıyor."],
      [594, "İneklerin nefesi ağırlaşıyor, çanlar artık yalnızca ara sıra, uykulu bir tınıyla kımıldıyor."],
      [648, "Osman kapının eşiğinde duruyor; serinleyen havayı, uzaktaki dereyi, sessizliği içine çekiyor."],
      [702, "Fenerin ışığı gitgide sönükleşiyor; ahır ılık, karanlık ve güvenli bir yuvaya dönüşüyor."],
      [756, "Her şey yavaşlıyor… çanlar susuyor, dere fısıldıyor, sen de o ılık samanın içine bırakıyorsun kendini…"],
    ],
  },
  {
    id: "s6", title: "Yıldız Haritacısı", dur: 10, sound: "wind", emoji: "🌌",
    lines: [
      [0, "Gözlerini yum, başını yastığa bırak; bedenin ağırlaşsın, her kasın usulca çözülsün."],
      [56, "Yavaşça nefes al ve ver. Şimdi seni yüksek bir dağın tepesindeki küçük gözlemeviyle buluşturuyorum."],
      [112, "Dışarıda ince bir rüzgâr esiyor; çam kokusunu, gecenin serin nefesini yumuşacık taşıyor."],
      [168, "İçeride astronom Defne, elinde kalemiyle geniş bir kâğıdın başında sabırla eğilmiş duruyor."],
      [224, "Önündeki masada buğusu tüten bir bardak çay; ıhlamur kokusu odayı sıcak bir örtüyle sarıyor."],
      [280, "Kubbenin ince yarığından gökyüzü görünüyor; sayısız yıldız, sessiz ve sakin, ağır ağır parlıyor."],
      [336, "Defne teleskopa eğiliyor; camın soğukluğu yanağına değiyor, gözü uzak bir ışık noktasına dalıyor."],
      [392, "Her yıldızı kâğıda usulca işaretliyor; kaleminin ucu ince, tatlı bir hışırtıyla kayıp gidiyor."],
      [448, "Aceleye yer yok; bir yıldız, bir nokta, bir çizgi… her hareket bir öncekinden daha yavaş."],
      [504, "Rüzgâr camlara hafifçe dokunuyor, uzaklaşıyor; sanki gökyüzü de derin bir nefes alıp veriyor."],
      [560, "Defne çayından bir yudum alıyor; ılıklık avuçlarından koluna, oradan tüm bedenine yayılıyor."],
      [616, "Yıldızlar kâğıtta yavaşça bir haritaya dönüşüyor; sabırlı, sessiz, telaşsız bir gece işi."],
      [672, "Gözkapakları ağırlaşıyor; kalemi masaya bırakıyor, sırtını sandalyeye yaslıyor, gökyüzüne bakıyor."],
      [728, "Rüzgâr iyice diniyor, yıldızlar süt gibi bir sessizliğe gömülüyor; her şey yumuşak ve uzak."],
      [784, "Defne gözlerini kapatıyor… yıldızlar hâlâ orada, sabırla parlıyor, sen de usulca kayıyorsun aralarına…"],
    ],
  },
  {
    id: "s7", title: "Sahafın Işığı", dur: 9, sound: "rain", emoji: "📚",
    lines: [
      [0, "Yorganını üzerine çek, başını yastığa göm; nefesin yavaşlasın, bedenin ağırlaşıp gevşesin."],
      [52, "Derin bir soluk al, usulca bırak. Şimdi seni yağmurlu bir akşamın küçük kitapçısına götürüyorum."],
      [104, "Dışarıda yağmur ince ince yağıyor; camın önünde damlalar birbirini kovalayarak süzülüyor."],
      [156, "İçeride yaşlı sahaf Kemal, kapanış saatinde raflar arasında ağır ağır dolaşıyor durmadan."],
      [208, "Her yandan eski kağıt kokusu yükseliyor; yıllanmış kitapların tatlı, tozlu, tanıdık nefesi."],
      [260, "Tavandan sarkan tek bir lamba var; sıcacık sarı ışığı raflara yumuşak bir örtü gibi seriliyor."],
      [312, "Kemal bir kitabı eline alıyor, sayfalarını usulca çeviriyor; kağıdın hışırtısı odaya yayılıyor."],
      [364, "Camdaki damlalar sokak lambasının ışığını yakalıyor, duvarda titrek altın lekeler dolaşıyor."],
      [416, "Yağmurun sesi eşit ve yumuşak; ne bir gök gürültüsü, ne telaş, yalnızca sabırlı bir tıpırtı."],
      [468, "Kemal kitabı yerine, en sevdiği rafa koyuyor; parmakları ciltlerin sırtında usulca geziyor."],
      [520, "Bir sandalyeye çöküyor; dizlerinde açık bir kitap, gözleri yorgun ama huzurlu, dingin."],
      [572, "Lambanın ışığı gitgide daha sıcak görünüyor; dükkân yağmurun sesiyle bir kozaya dönüşüyor."],
      [624, "Kemal sayfaya değil, artık camdaki damlalara bakıyor; her biri yavaşça aşağı süzülüyor."],
      [676, "Yağmur iyice hafifliyor, kitaplar sessizce uyuyor, ışık bir mum gibi usulca kısılıyor."],
      [730, "Kemal gözlerini kapatıyor… yağmur fısıldıyor, sayfalar dinleniyor, sen de o sıcak ışığa bırakıyorsun kendini…"],
    ],
  },
  {
    id: "s8", title: "Göl Evinde Yaz Gecesi", dur: 8, sound: "forest", emoji: "🛶",
    lines: [
      [0, "Yatağına iyice yerleş; sırtın yatağa gömülsün, omuzların usulca aşağı insin, çenen gevşesin."],
      [54, "Nefesin kendi kendine yavaşlasın; içeri giren serin hava, dışarı giden ılık bir iç çekiş olsun."],
      [108, "Elif, gölün kıyısındaki ahşap evin taraçasında, yumuşak bir hasır koltuğa gömülmüş oturuyor."],
      [162, "Akşam çoktan inmiş; gökyüzü lacivertten mürekkebe dönmüş, suyun üstünde soluk bir gümüş iz kalmış."],
      [216, "Ahşap duvarlar gün boyu emdiği sıcağı yavaşça geri veriyor; teni bu ılıklığı bir battaniye gibi duyuyor."],
      [270, "Uzaktan, kamışların ardından ağustos böceklerinin dinmeyen, uykulu şarkısı geliyor; tek tük, sonra hep birlikte."],
      [324, "Göl, iskelenin ayaklarına usulca dokunuyor; şıp, şıp, sonra sessizlik, sonra yine tembel bir şıpırtı."],
      [378, "Serin bir esinti çam iğnelerini ve ıslak toprağı taşıyor; Elif kokuyu içine çekiyor, göğsü genişliyor."],
      [432, "İskeleye doğru ağır adımlarla yürüyor; çıplak ayaklarının altında tahtalar hâlâ günün ılıklığını saklıyor."],
      [486, "Suya iyice yaklaşıp oturuyor; ayak parmaklarını serin göle daldırıyor, halkalar sessizce açılıp kayboluyor."],
      [540, "Karşı kıyıda tek bir sarı lamba yanıyor; ışığı suda titreşerek uzuyor, uzuyor, dağılıyor."],
      [594, "Başını arkaya yaslayıp gökyüzüne bakıyor; yıldızlar birer birer, aceleye kapılmadan ortaya çıkıyor."],
      [648, "Bir yerlerde bir balık suyun yüzünü öpüp geri iniyor; ses o kadar yumuşak ki neredeyse bir düşün içinde."],
      [702, "Esinti şimdi daha da hafif; sadece saçının bir telini okşuyor, sonra o da göl gibi durgunlaşıyor."],
      [756, "Elif göz kapaklarının ağırlaştığını duyuyor; su, böcekler, ılık tahta hepsi tek bir yumuşak uğultuya karışıyor."],
      [810, "Nefes veriyor, göl de onunla birlikte nefes veriyor; her şey yavaşlıyor, yavaşlıyor, dinginleşiyor…"],
    ],
  },
  {
    id: "s9", title: "Kervansarayın Avlusu", dur: 10, sound: "fire", emoji: "🏕️",
    lines: [
      [0, "Yastığına başını yumuşakça bırak; boynun desteklensin, kollarını yanlarına sal, avuçların açılsın."],
      [56, "Birkaç yavaş nefes al; her nefeste bir parça gerginlik omuzlarından kayıp gitsin, kaybolsun."],
      [112, "Meram, tozlu bir yolun sonunda, taş duvarlı eski bir kervansarayın kemerli kapısından içeri giriyor."],
      [168, "Uzun bir gün yürümüş; ama şimdi avlunun serinliği yüzüne değince, yorgunluğu tatlı bir ağırlığa dönüşüyor."],
      [224, "Avlunun ortasında bir ateş usulca yanıyor; alevler sarı, turuncu, en dipte mavi, hiç acele etmeden dans ediyor."],
      [280, "Yanan ardıç odununun kokusu havada asılı; Meram derin bir nefes çekiyor, göğsü bu ılık kokuyla doluyor."],
      [336, "Taş zeminin üstüne serilmiş kilime çöküyor; yün, gün boyu ateşin sıcağını içmiş, altında yumuşacık duruyor."],
      [392, "Çevresinde birkaç yolcu daha var; kimi çayını yudumluyor, kimi çoktan şalına sarılıp kıvrılmış, sessiz."],
      [448, "Biri alçak sesle uzak diyarların bir ezgisini mırıldanıyor; ne sözü belli, ne de bitişi; sadece sürükleniyor."],
      [504, "Meram başını kaldırıp gökyüzüne bakıyor; çöl göğü kapkara ve pırıl pırıl, yıldızlar sayısızca dökülüyor."],
      [560, "Ateşten yükselen kıvılcımlar bir an havada asılıyor, yıldızlara karışıyor, sonra usulca sönüyor."],
      [616, "Bir bardak ılık, tarçınlı çay avuçlarını ısıtıyor; sıcaklık parmaklarından bileklerine doğru yayılıyor."],
      [672, "Duvarların ardından gecenin serinliği geliyor; ama ateşin halkası içinde her şey ılık, güvenli, dingin."],
      [728, "Yolcuların fısıltıları giderek seyreliyor; ateşin çıtırtısı yavaşça tek başına kalıyor, uykulu bir ritim."],
      [784, "Meram göz kapaklarının ateşin ışığında ağırlaştığını duyuyor; başını şalına yaslıyor, kaslarını bırakıyor."],
      [840, "Alevler kısalıyor, kordan yumuşak bir kızıllık kalıyor; her şey yavaşlıyor, sönüyor, sessizliğe teslim oluyor…"],
    ],
  },
  {
    id: "s10", title: "Adanın Bahçıvanı", dur: 11, sound: "ocean", emoji: "🌺",
    lines: [
      [0, "Bedenini yatağına tümüyle bırak; ayaklarından başlayarak yukarı doğru her yerin gevşesin, ağırlaşsın."],
      [58, "Yavaşça nefes al ve ver; nefesin, kıyıya vuran bir dalga kadar sakin, bir o kadar düzenli olsun."],
      [116, "Kaptan Kerim, uzak bir adanın tepesindeki botanik bahçede, akşamın altın ışığında usulca dolaşıyor."],
      [174, "Yıllardır bu bahçeye bakıyor; her patikayı, her yaprağı, günün her rengini avucunun içi gibi biliyor."],
      [232, "Güneş denize doğru alçalıyor; ışık ballaşıyor, yaprakların üstünde sıcak, bakır bir parıltı bırakıyor."],
      [290, "Aşağıdan, kayalıklardan denizin dingin uğultusu geliyor; dalgalar geliyor, çekiliyor, yine geliyor."],
      [348, "Kerim eski bakır kovasını alıp yasemin sıralarını suluyor; su, kuru toprağa değince tatlı bir toprak kokusu yükseliyor."],
      [406, "Serin bir deniz meltemi bahçeyi dolaşıyor; yasemin, açelya ve tuzlu havanın kokusunu birbirine karıştırıyor."],
      [464, "Bir hercai menekşe tarhının önünde duruyor; parmak uçlarıyla ıslak yaprakları usulca okşuyor, gülümsüyor."],
      [522, "Su, çiçeklerin dibinde küçük parlak birikintiler yapıyor; akşam ışığını yakalayıp minik aynalar gibi titriyor."],
      [580, "Meltem gitgide yumuşuyor; sadece en uçtaki palmiyenin yapraklarını hafifçe hışırdatıp geçiyor, sonra diniyor."],
      [638, "Kerim kovasını bırakıp taş bir banka oturuyor; sırtı gün boyu ısınmış taşın ılıklığını hissediyor."],
      [696, "Ufukta güneşin son dilimi denize karışıyor; gökyüzü şeftaliden mora, mordan koyu bir maviye dönüyor."],
      [754, "Çiçekler akşamla birlikte kokularını daha da salıyor; hava artık ağır, tatlı, uykulu bir baldan yapılmış gibi."],
      [812, "Kerim göz kapaklarının deniz kadar ağırlaştığını duyuyor; dalgaların sesi giderek uzaklaşıp yumuşuyor."],
      [870, "Son bir nefes veriyor; bahçe, deniz, meltem hepsi birlikte yavaşlıyor, kararıyor, sessizce uykuya bırakıyor…"],
    ],
  },
];

/* Nefes egzersizleri */
const BREATHS = [
  { id: "b478", name: "4-7-8 Uyku Nefesi", desc: "Uykudan önce sinir sistemini yavaşlatır", inhale: 4, hold: 7, exhale: 8, hold2: 0, cycles: 4, emoji: "😴" },
  { id: "bbox", name: "Kutu Nefesi", desc: "Odak ve sakinlik için 4-4-4-4", inhale: 4, hold: 4, exhale: 4, hold2: 4, cycles: 5, emoji: "📦" },
  { id: "bcalm", name: "Sakinleşme Nefesi", desc: "Uzun verişle anında rahatlama", inhale: 4, hold: 0, exhale: 6, hold2: 0, cycles: 6, emoji: "🍃" },
];

/* Sesler — WebAudio ile sentezlenir, telif yok. Karışım masasında birlikte çalınabilir. */
const SOUNDS = [
  { id: "rain",    name: "Yağmur",        icon: "rain" },
  { id: "ocean",   name: "Okyanus",       icon: "ocean" },
  { id: "selale",  name: "Şelale",        icon: "waterfall" },
  { id: "ciftlik", name: "Çiftlik",       icon: "farm" },
  { id: "wind",    name: "Rüzgâr",        icon: "wind" },
  { id: "fire",    name: "Şömine",        icon: "fire" },
  { id: "forest",  name: "Gece Ormanı",   icon: "forest" },
  { id: "white",   name: "Beyaz Gürültü", icon: "radio" },
  { id: "brown",   name: "Kahverengi Gürültü", icon: "noise" },
  { id: "pink",    name: "Pembe Gürültü", icon: "noise" },
  { id: "f174",    name: "174 Hz Dinginlik", icon: "tone" },
  { id: "f432",    name: "432 Hz Uyum",   icon: "tone" },
];

/* Günün sözleri — özgün */
const QUOTES = [
  "Nefesin, her zaman yanında taşıdığın bir eve açılan kapıdır.",
  "Zihnin bir gökyüzü; düşünceler sadece geçen bulutlar.",
  "Bugün yapabileceğin en cesur şey, durup dinlenmek olabilir.",
  "Fırtınayı durduramazsın ama limanını kendi içinde kurabilirsin.",
  "Küçük bir mola, büyük bir devam ediştir.",
  "Kendine bir dostuna davrandığın gibi davran; o dostu hak ediyorsun.",
  "Uyku, yarına yazılmış en nazik mektuptur.",
  "Aceleyle geçen bir gün değil, fark ederek geçen bir an zenginliktir.",
  "Sakinlik bir yetenek değil, her gün sulanan bir bahçedir.",
  "Şu an buradasın; bu, başlamak için yeterli.",
  "Bırakmak kaybetmek değildir; ellerini yeni şeyler için boşaltmaktır.",
  "En derin sessizlik, iki nefes arasındaki o küçük boşluktadır.",
  "Yorgunluğunu kabul etmek de bir güç gösterisidir.",
  "Gökyüzüne bak: bu kadar genişlik, senin içinde de var.",
];

/* Yolculuklar / programlar — days: MEDITATIONS id listesi (sırayla) */
const PROGRAMS = [
  {
    id: "p7giris", title: "7 Günde Meditasyona Giriş", emoji: "🌄", tag: "YOLCULUK",
    desc: "Hiç yapmadıysan buradan başla — her gün yeni bir beceri",
    days: ["m13", "m14", "m15", "m16", "m17", "m18", "m19"],
  },
  {
    id: "pstres", title: "Stresi Bırak", emoji: "🍃", tag: "PROGRAM",
    desc: "5 seansta gerginliği tanı, gevşet, bırak",
    days: ["m20", "m1", "m2", "m28", "m11"],
  },
];

/* Toplu seanslar — senkronu saat sağlar: herkes aynı dakikada aynı içerikte.
   taban: katılımcı sayacının çekirdeği (v2'de gerçek sayaca bağlanacak) */
const TOPLU_SEANSLAR = [
  { id: "sabah", saat: "08:00", ad: "Güne Birlikte Başla", emoji: "☀️", icerik: "m11", taban: 1140 },
  { id: "ogle",  saat: "13:00", ad: "Öğle Molası",         emoji: "🍃", icerik: "m20", taban: 720 },
  { id: "gece",  saat: "22:00", ad: "Ay Işığı Seansı",     emoji: "🌕", icerik: "m22", taban: 3080 },
];

/* Rozetler — koşullar app.js/checkBadges içinde */
const BADGES = [
  { id: "ilkadim",  emoji: "🌱", name: "İlk Adım",    desc: "İlk seansını tamamla" },
  { id: "seri3",    emoji: "🔥", name: "3 Gün Seri",  desc: "3 gün üst üste seans yap" },
  { id: "seri7",    emoji: "⚡", name: "7 Gün Seri",  desc: "Bir hafta aralıksız" },
  { id: "seri30",   emoji: "🏆", name: "30 Gün Seri", desc: "Bir ay aralıksız" },
  { id: "saat1",    emoji: "⏳", name: "1 Saat",      desc: "Toplam 60 dakika tamamla" },
  { id: "saat10",   emoji: "🌟", name: "10 Saat",     desc: "Toplam 600 dakika tamamla" },
  { id: "gecekusu", emoji: "🦉", name: "Gece Kuşu",   desc: "22:00'den sonra bir seans yap" },
  { id: "erkenkus", emoji: "🐦", name: "Erken Kuş",   desc: "08:00'den önce bir seans yap" },
  { id: "kasif",    emoji: "🧭", name: "Kâşif",       desc: "5 farklı kategoriden seans yap" },
  { id: "yolcu",    emoji: "🎒", name: "Yolcu",       desc: "Bir yolculuğu baştan sona bitir" },
];
